version: "3"

services:
  db:
    image: postgres
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./harue/persist:/var/lib/postgresql/data
      - ./harue/initdb:/docker-entrypoint-initdb.d
  redis:
    image: redis
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  teru:
    image: rolevax/teru
    ports:
      - 8080:8080
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./harue/ssl:/srv:ro
    depends_on:
      - db
      - redis

