version: "3"

services:
  db:
    image: postgres
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./harue/persist:/var/lib/postgresql/data
      - ./harue/initdb:/docker-entrypoint-initdb.d
    logging:
      options:
        max-size: 16m
  redis:
    image: redis
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./harue/cache:/data
    logging:
      options:
        max-size: 16m
  teru:
    image: rolevax/teru
    ports:
      - 8080:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./harue/res:/srv:ro
    depends_on:
      - db
      - redis
    logging:
      options:
        max-size: 16m
  toki:
    image: rolevax/toki
    volumes:
      - /etc/localtime:/etc/localtime:ro
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 3s
    logging:
      options:
        max-size: 16m
  hisa:
    image: rolevax/hisa
    ports:
      - 6171:6171
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - db
      - redis
      - toki
    logging:
      options:
        max-size: 16m

